//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartH2O_SeeApp.SmartH2O_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartH2O_Service.WebService_Interface")]
    public interface WebService_Interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToAlarmsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToAlarmsLogResponse")]
        void WriteToAlarmsLog(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToAlarmsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToAlarmsLogResponse")]
        System.Threading.Tasks.Task WriteToAlarmsLogAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToSensorsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToSensorsLogResponse")]
        void WriteToSensorsLog(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToSensorsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToSensorsLogResponse")]
        System.Threading.Tasks.Task WriteToSensorsLogAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetHourlyInformation", ReplyAction="http://tempuri.org/WebService_Interface/GetHourlyInformationResponse")]
        string GetHourlyInformation(string paramType, string specificDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetHourlyInformation", ReplyAction="http://tempuri.org/WebService_Interface/GetHourlyInformationResponse")]
        System.Threading.Tasks.Task<string> GetHourlyInformationAsync(string paramType, string specificDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetDailyInformation", ReplyAction="http://tempuri.org/WebService_Interface/GetDailyInformationResponse")]
        string GetDailyInformation(string paramType, string firstDate, string secondDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetDailyInformation", ReplyAction="http://tempuri.org/WebService_Interface/GetDailyInformationResponse")]
        System.Threading.Tasks.Task<string> GetDailyInformationAsync(string paramType, string firstDate, string secondDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetWeeklyInformation", ReplyAction="http://tempuri.org/WebService_Interface/GetWeeklyInformationResponse")]
        string GetWeeklyInformation(string paramType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetWeeklyInformation", ReplyAction="http://tempuri.org/WebService_Interface/GetWeeklyInformationResponse")]
        System.Threading.Tasks.Task<string> GetWeeklyInformationAsync(string paramType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetDailyAlarms", ReplyAction="http://tempuri.org/WebService_Interface/GetDailyAlarmsResponse")]
        string[] GetDailyAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetDailyAlarms", ReplyAction="http://tempuri.org/WebService_Interface/GetDailyAlarmsResponse")]
        System.Threading.Tasks.Task<string[]> GetDailyAlarmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetAlarmsByDates", ReplyAction="http://tempuri.org/WebService_Interface/GetAlarmsByDatesResponse")]
        string[] GetAlarmsByDates(string firstDate, string secondDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetAlarmsByDates", ReplyAction="http://tempuri.org/WebService_Interface/GetAlarmsByDatesResponse")]
        System.Threading.Tasks.Task<string[]> GetAlarmsByDatesAsync(string firstDate, string secondDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetParamLogDates", ReplyAction="http://tempuri.org/WebService_Interface/GetParamLogDatesResponse")]
        string[] GetParamLogDates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetParamLogDates", ReplyAction="http://tempuri.org/WebService_Interface/GetParamLogDatesResponse")]
        System.Threading.Tasks.Task<string[]> GetParamLogDatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetAlarmLogDates", ReplyAction="http://tempuri.org/WebService_Interface/GetAlarmLogDatesResponse")]
        string[] GetAlarmLogDates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/GetAlarmLogDates", ReplyAction="http://tempuri.org/WebService_Interface/GetAlarmLogDatesResponse")]
        System.Threading.Tasks.Task<string[]> GetAlarmLogDatesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_InterfaceChannel : SmartH2O_SeeApp.SmartH2O_Service.WebService_Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_InterfaceClient : System.ServiceModel.ClientBase<SmartH2O_SeeApp.SmartH2O_Service.WebService_Interface>, SmartH2O_SeeApp.SmartH2O_Service.WebService_Interface {
        
        public WebService_InterfaceClient() {
        }
        
        public WebService_InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteToAlarmsLog(string[] data) {
            base.Channel.WriteToAlarmsLog(data);
        }
        
        public System.Threading.Tasks.Task WriteToAlarmsLogAsync(string[] data) {
            return base.Channel.WriteToAlarmsLogAsync(data);
        }
        
        public void WriteToSensorsLog(string[] data) {
            base.Channel.WriteToSensorsLog(data);
        }
        
        public System.Threading.Tasks.Task WriteToSensorsLogAsync(string[] data) {
            return base.Channel.WriteToSensorsLogAsync(data);
        }
        
        public string GetHourlyInformation(string paramType, string specificDate) {
            return base.Channel.GetHourlyInformation(paramType, specificDate);
        }
        
        public System.Threading.Tasks.Task<string> GetHourlyInformationAsync(string paramType, string specificDate) {
            return base.Channel.GetHourlyInformationAsync(paramType, specificDate);
        }
        
        public string GetDailyInformation(string paramType, string firstDate, string secondDate) {
            return base.Channel.GetDailyInformation(paramType, firstDate, secondDate);
        }
        
        public System.Threading.Tasks.Task<string> GetDailyInformationAsync(string paramType, string firstDate, string secondDate) {
            return base.Channel.GetDailyInformationAsync(paramType, firstDate, secondDate);
        }
        
        public string GetWeeklyInformation(string paramType) {
            return base.Channel.GetWeeklyInformation(paramType);
        }
        
        public System.Threading.Tasks.Task<string> GetWeeklyInformationAsync(string paramType) {
            return base.Channel.GetWeeklyInformationAsync(paramType);
        }
        
        public string[] GetDailyAlarms() {
            return base.Channel.GetDailyAlarms();
        }
        
        public System.Threading.Tasks.Task<string[]> GetDailyAlarmsAsync() {
            return base.Channel.GetDailyAlarmsAsync();
        }
        
        public string[] GetAlarmsByDates(string firstDate, string secondDate) {
            return base.Channel.GetAlarmsByDates(firstDate, secondDate);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAlarmsByDatesAsync(string firstDate, string secondDate) {
            return base.Channel.GetAlarmsByDatesAsync(firstDate, secondDate);
        }
        
        public string[] GetParamLogDates() {
            return base.Channel.GetParamLogDates();
        }
        
        public System.Threading.Tasks.Task<string[]> GetParamLogDatesAsync() {
            return base.Channel.GetParamLogDatesAsync();
        }
        
        public string[] GetAlarmLogDates() {
            return base.Channel.GetAlarmLogDates();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAlarmLogDatesAsync() {
            return base.Channel.GetAlarmLogDatesAsync();
        }
    }
}
