//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartH2O_DLog.SmartH2O_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartH2O_Service.WebService_Interface")]
    public interface WebService_Interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToAlarmsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToAlarmsLogResponse")]
        void WriteToAlarmsLog(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToAlarmsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToAlarmsLogResponse")]
        System.Threading.Tasks.Task WriteToAlarmsLogAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToSensorsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToSensorsLogResponse")]
        void WriteToSensorsLog(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_Interface/WriteToSensorsLog", ReplyAction="http://tempuri.org/WebService_Interface/WriteToSensorsLogResponse")]
        System.Threading.Tasks.Task WriteToSensorsLogAsync(string[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_InterfaceChannel : SmartH2O_DLog.SmartH2O_Service.WebService_Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_InterfaceClient : System.ServiceModel.ClientBase<SmartH2O_DLog.SmartH2O_Service.WebService_Interface>, SmartH2O_DLog.SmartH2O_Service.WebService_Interface {
        
        public WebService_InterfaceClient() {
        }
        
        public WebService_InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteToAlarmsLog(string[] data) {
            base.Channel.WriteToAlarmsLog(data);
        }
        
        public System.Threading.Tasks.Task WriteToAlarmsLogAsync(string[] data) {
            return base.Channel.WriteToAlarmsLogAsync(data);
        }
        
        public void WriteToSensorsLog(string[] data) {
            base.Channel.WriteToSensorsLog(data);
        }
        
        public System.Threading.Tasks.Task WriteToSensorsLogAsync(string[] data) {
            return base.Channel.WriteToSensorsLogAsync(data);
        }
    }
}
